services:
  - type: web
    name: pdf-merger-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 5000
      - key: BASE_URL
        value: 0.0.0.0
      - key: MONGODB_URI
        fromService:
          name: pdf-merger-database
          type: database
          property: connectionString
  - type: database
    name: pdf-merger-database
    env: mongodb
    ipAllowList: []
    plan: free
